[package]
name = "leetcode"
version = "0.1.0"
authors = ["Adrian Cruz <drincruz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day01"
src = "src/day01.rs"

[[bin]]
name = "day02"
src = "src/day02.rs"
